services:
  euser-safaris-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: euser-safaris-web
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - safari-network

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-safari
    restart: always
    volumes:
      - C:\Users\hp\.cloudflared:/etc/cloudflared
    command: tunnel --config /etc/cloudflared/config.yml run
    networks:
      - safari-network
    depends_on:
      - euser-safaris-web

networks:
  safari-network:
    external: true
